### ISSUE TITLE
Delete row in cmm_data table if coinmarketcap returns nothing

### ISSUE THREAD

**Issue by tzanko-matev** [santiment/sanbase#1]
If the Coinmarketcap API stops returning data for some ticker we should delete it from cmm_data. Otherwise we show old info. This happened with Centra(CTR)

**Comment by ikabankin** [comment]
Update from recent team-general discuss talks:

In case of Coinmarketcap API stops returning data for some ticker do not delete the whole raw, do display "No data" instead of missing data.
